baseurl = "https://dowwie.github.io/"
languageCode = "en-EN"
title = "Darin Gordon"
paginate = 5
DisqusShortname = "dowwie"
Copyright = "All rights reserved - 2016"
theme = "casper"
canonifyurls = false 
[params]
  description = ""
  cover = "images/cover.jpg"
  author = "Darin Gordon"
  authorlocation = "New Jersey, USA"
  authorwebsite = "http://www.daringordon.com"
  bio= "Entrepreneur"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-60351215-1"
  githubName = "dowwie"
  twitterName = "darin_gordon"
  hideHUGOSupport = true


[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github repos"
  weight = 100
  pre = "<h3>Github</h3>"
  url = "https://github.com/dowwie"

[[menu.main]]
  name = "Twitter"
  weight = 101
  url = "https://twitter.com/darin_gordon"

[[menu.main]]
  name = "EMail"
  weight = 101
  pre = "<h3>Contact Me</h3>"
  url = "mailto:dkcdkg@gmail.com"

[[menu.main]]
  name = "Keybase"
  weight = 101
  pre = "<h3>KeybaseIO</h3>"
  url = "https://keybase.io/dowwie"
